### ISSUE TITLE
Modify zenhub attributes of a ticket

### ISSUE THREAD

**Issue by kofalt** [ZenHubIO/API#10]
Hey guys, new API looks great! :+1: 

I was wondering if you have plans to add routes for modifying the zenhub attributes of a ticket - estimate and pipeline, for example. Now that the [Multi Repo Burndown](https://www.zenhub.io/blog/better-progress-tracking-with-multi-repo-burndown-charts/) charts are out, we were thinking of doing some creative issue-editing.

**Comment by azenMatt** [comment]
thanks @kofalt - this is on the roadmap, but not yet prioritized. 

Il keep you updated with when we think we will be able to get this live for everyone

**Comment by andrewlow** [comment]
I'll open a new issue if needed, but I'd like to have this cover the ability to modify the position of zenhub issues via the API. It seems that today the API is read only entirely.

**Comment by azenMatt** [comment]
Hi @andrewlow - currently the API is read only. 

I have created - https://github.com/ZenHubIO/API/issues/24 - to track the write option of position within a pipeline to make sure it does not get lost. 

I don't have an ETA right now, but we will be looking to make a write access API available in the future.

**Comment by azenMatt** [comment]
The ZenHub write API is now live :) 

This includes the ability to change ZenHub data such as pipeline / estimate / epics 

Let me know if this is useful for your teams!

**Comment by kofalt** [comment]
Awesome! Thanks @azenMatt!
