### ISSUE TITLE
JS error on Projects tab

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/API#101]
Windows 10
Chrome v70.0.3538.77
ZenHub v2.38.4

After opening the Project tab, I can't switch to the ZenHub tab.

In the console, I see these two errors occuring in `chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js`:

<details>
<summary>Error 1</summary>

> main.js:1 Mon Oct 29 2018 08:53:38 GMT-0500 (Central Daylight Time) "jquery.assert" "/StylishThemes/GitHub-Dark/projects" "looking for undefined, expect: 1, actual: 0"
t.error @ main.js:1
r.fn.assertFound @ main.js:1
contentChangeStream @ main.js:1
_watchPjaxChange @ main.js:1
loadFeatures @ main.js:1
_loadPage @ main.js:1
enterRepoPage @ main.js:1
(anonymous) @ main.js:1
execute @ vendor.js:50
(anonymous) @ vendor.js:50
(anonymous) @ vendor.js:50
g.some.g.any @ vendor.js:50
loadUrl @ vendor.js:50
start @ vendor.js:50
start @ main.js:1
initialize @ main.js:1
e.Model @ vendor.js:50
r @ vendor.js:50
(anonymous) @ main.js:1
s @ main.js:1
(anonymous) @ main.js:1
s @ main.js:1
(anonymous) @ main.js:1
s @ main.js:1
n @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
</details>

<details>
<summary>Error 2</summary>

> Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at Object.contentChangeStream (main.js:1)
    at r._watchPjaxChange (main.js:1)
    at r.loadFeatures (main.js:1)
    at r._loadPage (main.js:1)
    at r.enterRepoPage (main.js:1)
    at r.<anonymous> (main.js:1)
    at r.execute (vendor.js:50)
    at Object.callback (vendor.js:50)
    at vendor.js:50
    at Function.g.some.g.any (vendor.js:50)
contentChangeStream @ main.js:1
_watchPjaxChange @ main.js:1
loadFeatures @ main.js:1
_loadPage @ main.js:1
enterRepoPage @ main.js:1
(anonymous) @ main.js:1
execute @ vendor.js:50
(anonymous) @ vendor.js:50
(anonymous) @ vendor.js:50
g.some.g.any @ vendor.js:50
loadUrl @ vendor.js:50
start @ vendor.js:50
start @ main.js:1
initialize @ main.js:1
e.Model @ vendor.js:50
r @ vendor.js:50
(anonymous) @ main.js:1
s @ main.js:1
(anonymous) @ main.js:1
s @ main.js:1
(anonymous) @ main.js:1
s @ main.js:1
n @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
</details>

**Comment by kendramoroz** [comment]
👋 Hey @Mottie Thanks for sending this our way - please reach out to the GitHub Support team for further debugging as Projects is a native GitHub feature and not part of the ZenHub experience.

**Comment by Mottie** [comment]
Please review the errors again... they are occurring in the ZenHub extension code, not GitHub's code.
