### ISSUE TITLE
Provide access to 'Milestone start date'

### ISSUE THREAD

**Issue by azenMatt** [ZenHubIO/API#14]
This is a ZenHub attribute not currently exposed via the API that is useful for reporting

**Comment by mhelvens** [comment]
Big +1 on this one. ZenHub itself still lacks editing functionality for milestones altogether (ZenHubIO/support#597).

I needed to shift some dates around for 9 milestones across 7 repos (= 63). I used the GitHub API for that. But then I noticed that our burn-down charts were still messed up. Of course... I didn't change the start dates.

Until this endpoint exists, I believe the only way to fix our milestones is to delete all of them (manually or by using the GitHub API) and then to recreate them again through the ZenHub interface.

If I'm missing something, please let me know.

**Comment by azenMatt** [comment]
The other (still painful) way to solve this problem is to edit the start date in the burndown chart view for each milestone.

In order to access each one, you will need to load the burndown chart in each separate repository and update the start date there

**Comment by azenMatt** [comment]
(so I agree that this needs to be both easier in the interface, and on the API!)

**Comment by mhelvens** [comment]
> The other (still painful) way to solve this problem is to edit the start date in the burndown chart view for each milestone.
> In order to access each one, you will need to load the burndown chart in each separate repository and update the start date there

Actually, it seems I can edit the start-date there for all repos at the same time! So that helped me out. Thanks! :+1: (For the end-date, though, the edit button still sends us to vanilla GitHub.)

**Comment by pnavarrc** [comment]
Hey, Pablo from ZenHub. We released a new set of endpoints, including the ability to [set and get the milestone start date](https://github.com/ZenHubIO/API#milestones). Let us know if you have any feedback!
