### ISSUE TITLE
Add Epics to API 

### ISSUE THREAD

**Issue by azenMatt** [ZenHubIO/API#19]
- [ ]  Epic end point to display all issues inside a given epic 
- [ ] Ability to get all epics in a repo 
- [ ] Add isEpic flag to existing methods 

What else would be useful here?

**Comment by garyharan** [comment]
`GET https://api.zenhub.io/p1/repositories/:repo_id/epics/`
`GET https://api.zenhub.io/p1/repositories/:repo_id/epics/:epic_id/issues`

**Comment by aaronwest** [comment]
Another topic for discussion is how to best handle returning points estimates in the API when an issue has the `isEpic` flag. I'd vote for summing the estimates of the underlying issues. I commented more on this in [the following issue](https://github.com/ZenHubIO/support/issues/674#issuecomment-215528438) as it is tangentially related.

**Comment by mogul** [comment]
I'd like the ability to set which issues are in an epic.

**Comment by aaronwest** [comment]
> I'd like the ability to set which issues are in an epic.

I like the ZenHub plugin UI for adding issues to Epics. But I can see how having this functionality in the API would also be nice.

**Comment by jjaquinta** [comment]
I need this in a major way, right now. Got a mandate for reporting from the bean counters that needs me to add up story points. If I can't work out which epic an issue belongs to I can't work out the correct totals. Do we have a timetable on this?

**Comment by azenMatt** [comment]
@jjaquinta - let me confirm and i will get back to you on this one

**Comment by ConorsSuperHappyFuntimeAccount** [comment]
I also need this asap, and for similar reasons.

**Comment by aaronwest** [comment]
> @jjaquinta - let me confirm and i will get back to you on this one

Hey @azenMatt, hope you're well! Do you have any updated information on the timing of this issue?

**Comment by azenMatt** [comment]
Hi @aaronwest - this just got including in out current sprint :) so will be with you soon! 

@olegzd is going to be taking care of it - we will share some thought on how the end point will look before it gets built to make sure it meets what everyone needs

**Comment by aaronwest** [comment]
@azenMatt - great, thanks for the heads up.

**Comment by olegzd** [comment]
Hi @aaronwest, going to be releasing the new routes soon. How does the following sound to you?



**To get the list of epics for a repository:**

```
GET https://api.zenhub.io/p1/repositories/:repo_id/epics/
```

will return 

```
{
  "epic_issues": [
    {
      "issue_number": 1
    },
    {
      "issue_number": 2
    },
    {
      "issue_number": 3
    },
    {
      "issue_number": 4
    }
  ]
}
```

**To get a list of issues belonging to an epic + metadata for each, along with total epic estimate (@jjaquinta)**:

```
GET https://api.zenhub.io/p1/repositories/:repo_id/epics/:issue_number
```

will return

```
{
  "total_epic_estimates": 160,
  "issues": [
    {
      "issue_number": 47,
      "is_epic": false,
      "estimate": {
        "value": 40
      },
      "pipeline": {
        "name": "Icebox"
      }
    },
    {
      "issue_number": 48,
      "is_epic": false
    },
    {
      "issue_number": 49,
      "is_epic": false,
      "estimate": {
        "value": 40
      },
      "pipeline": {
        "name": "Backlog"
      }
    },
    {
      "issue_number": 50,
      "is_epic": false
    },
    {
      "issue_number": 51,
      "is_epic": true,
      "estimate": {
        "value": 40
      },
      "pipeline": {
        "name": "In Progress"
      }
    },
    {
      "issue_number": 52,
      "is_epic": false
    }
  ],
  "estimate": {
    "value": 40
  },
  "pipeline": {
    "name": "Review/QA"
  }
}
```

**Comment by aaronwest** [comment]
@olegzd thanks for the info and my apologies for taking weeks to get back to you! Here are some thoughts.



> To get the list of epics for a repository:
> 
> GET https://api.zenhub.io/p1/repositories/:repo_id/epics/
> will return
> 
> {
>   "epic_issues": [
>     {
>       "issue_number": 1
>     },
>     {
>       "issue_number": 2
>     },
>     {
>       "issue_number": 3
>     },
>     {
>       "issue_number": 4
>     }
>   ]
> }

That looks okay. I think it would also be good to include the GitHub link for each item in `epic_issues[]`.

> To get a list of issues belonging to an epic + metadata for each, along with total epic estimate (@jjaquinta):
> 
> GET https://api.zenhub.io/p1/repositories/:repo_id/epics/:issue_number

Will this endpoint nest the epic information returned? In other words, if one of the items in `issues[]` has `is_epic: true` will it include nested issues or would a subsequent call to `https://api.zenhub.io/p1/repositories/:repo_id/epics/:issue_number` be required?

Lastly, I want to circle back on this comment of mine:

>Another topic for discussion is how to best handle returning points estimates in the API when an issue has the isEpic flag. I'd vote for summing the estimates of the underlying issues.

Will the values in `issues[].estimate.value` be cumulative or will it represent the single estimate value associated with the issue.

Thanks for the hard work on this team!

**Comment by olegzd** [comment]
@aaronwest Thanks for the feedback!

> That looks okay. I think it would also be good to include the GitHub link for each item in epic_issues[]

Goodl call  - I'll add that in.

 > Will this endpoint nest the epic information returned? In other words, if one of the items in issues[] has is_epic: true will it include nested issues or would a subsequent call to https://api.zenhub.io/p1/repositories/:repo_id/epics/:issue_number be required?

You would need to make additional calls, otherwise we risk the response being too big, and would need to introduce pagination (do-able, but more complex for anyone digesting the API).


> Will the values in issues[].estimate.value be cumulative or will it represent the single estimate value associated with the issue 

`{ issues: [`issueNumber`].estimate.value }` will represent the single estimate for `issueNumber`. 
For the total epic estimate (SUM of the estimate of the epic itself, and all of its individual issue estimates belonging to the epic (first level), you can access
`{ total_epic_estimates: 99 }`

**Comment by aaronwest** [comment]
> For the total epic estimate (SUM of the estimate of the epic itself, and all of its individual issue estimates belonging to the epic (first level), you can access
> { total_epic_estimates: 99 }

@olegzd awesome, that's perfect. I now see I missed the _total_epic_estimates_ key in your original comment. I think this will work quite well.

Do you plan on updating the existing endpoint - `https://api.zenhub.io/p1/repositories/:repo_id/issues/:issue_number` - such that it also returns `total_epic_estimates` if appropriate? One of my use cases involves looking at all completed GitHub issues in a given month and retrieving the ZenHub estimate for each issue. Currently, the estimate returned is only for the given issue number even if the issue is configured as an Epic issue with sub-issues. I'd like to have some way to get the cumulative value and `total_epic_estimates` would be perfect for this. For more on this use case see [this comment](https://github.com/ZenHubIO/support/issues/674#issuecomment-215528438) I wrote.

**Comment by olegzd** [comment]
@aaronwest 

> https://api.zenhub.io/p1/repositories/:repo_id/issues/:issue_number - such that it also returns total_epic_estimates

We'd like to keep that route separate from Epics meta-info that you would be able to get from the new route. Reason is to avoid it from bloating. However, 

`GET https://api.zenhub.io/p1/repositories/:repo_id/issues/:issue_number`

will now include an `is_epic` key with value `true/false`. I'm hoping that will help your use case in the following way:

```
for i in issues:
    if i.is_epic:
        fetch epic info for i; get total epic estimates
```

**Comment by aaronwest** [comment]
I can make that work. Thanks @olegzd.

**Comment by olegzd** [comment]
Epics API support has been added to our API.

API documentation has been updated(see https://github.com/ZenHubIO/API/pull/31).

Few minor changes from the comments above: 

```
GET https://api.zenhub.io/p1/repositories/:repo_id/epics/:issue_number
```

returns total epic estimates as 

```json
"total_epic_estimates": {
    "value": 60
  }
```

rather than 

```json
"total_epic_estimates": 60
```
 to align it with our existing API.
