### ISSUE TITLE
Add issue pipeline changes to API [request]

### ISSUE THREAD

**Issue by hwhopemaIBM** [ZenHubIO/API#20]
We would like to be able to use the API to modify the issue's pipeline column. I.e. move an issue from In Progress to Review.

**Comment by emremangir** [comment]
+1 for this. @hwhopemaIBM it looks like this is something that's been requested but hasn't yet been assigned a timeline (at least publicly...)
https://github.com/ZenHubIO/support/issues/554

**Comment by mpaler** [comment]
+1

**Comment by kaufers** [comment]
+1

**Comment by ryderstorm** [comment]
+1

**Comment by hallerm** [comment]
Really need this to streamline the clunkiness of pull requests.
+1

**Comment by wonganut** [comment]
with this feature , it would encourage ppl from moving from other platform to zenhub on github. there are several tools doing the same as zenhub and during transition, slowly move from legacy tool to this zenhub.

**Comment by azenMatt** [comment]
We just launched a number of new endpoints for the API - including Write access for moving an Issue between pipelines, you can see the details here! 

https://github.com/ZenHubIO/API#move-issue-between-pipelines

**Comment by themyth92** [comment]
Hi, are there any ways to move the issue between pipeline but specify who does it ? For now from what I see on Github, the one who does moving the issue is based on the owner of Zenhub Token.
