### ISSUE TITLE
Add Issue To Epic Via API?

### ISSUE THREAD

**Issue by gamename** [ZenHubIO/API#22]
Hi,

How do I add an existing issue to an Epic via the API?

THanks,
-T

**Comment by kendramoroz** [comment]
@gamename Kendra here from the ZenHub team 👋  I'm doing a sweep of the support board and stumbled upon your question here. I know it's been a while, but figured I'd let you know if you're still curious—The ZenHub API is currently read-only so you can only pull information out. 

Let me know if there's anything else I can help with!
