### ISSUE TITLE
Add Epic API data to ZenHub Enterprise 

### ISSUE THREAD

**Issue by rcuen** [ZenHubIO/API#32]
Hi

I was trying to get an issue data (/repositories/:repo_id/issues/:issue_number), the documentation says the endpoint returns that issue's assigned Time Estimate (if applicable), its Pipeline in the Board, an is **epic flag (true/false)**, as well as any +1s.

I tried with several issues, but the JSON never returns the "is epic" flag.

Thanks!

**Comment by olegzd** [comment]
Hi @rcuen, can you send us an email - support@zenhub.com, I'll take a look at your issue ASAP.

If you can provide the organization/repository, that would help us track down the issue.

**Comment by azenMatt** [comment]
Updating the title here to reflect that this is due to the Epic API not being present on ZenHub Enterprise until the Q4 release.

**Comment by azenMatt** [comment]
closing this issues as ZHE 2.13 which includes these Epic changes has just gone live
