### ISSUE TITLE
Add issues to an Epic / convert to Epic 

### ISSUE THREAD

**Issue by azenMatt** [ZenHubIO/API#35]
@gamename commented on [Sun Oct 16 2016](https://github.com/ZenHubIO/support/issues/927)

Hi,

Can your API associate issues with an epic?
Also, can your API convert an issue into an epic?

Thanks,
-T

---

@azenMatt commented on [Sun Oct 16 2016](https://github.com/ZenHubIO/support/issues/927#issuecomment-254067887)

Hi @gamename - currently the ZenHub API is read only access so we can't perform either of those actions. 

Im going to move this issue over to the API repo where we will be providing updates on write access as we work towards it

**Comment by gamename** [comment]
Thanks @azenMatt! I should tell you I'm at NextGxDx and we (as usual) are happy to beta test anything you guys build.

**Comment by azenMatt** [comment]
Hi @gamename  - we just released some new API endpoints, include convert to Epic / add to Epic

https://github.com/ZenHubIO/API#convert-issue-to-epic

Let me know if these help!

**Comment by paltman** [comment]
I'm trying to call that endpoint with a list of issues to add to the issue I'm converting and getting 400 response, which the docs say mean that it's already an Epic, however, in the UI there is no indication that it is.

**Comment by paltman** [comment]
The data I'm sending looks like:

```json
{"issues": [{"repo_id": 89558527, "issue_number": 611}, {"repo_id": 89558527, "issue_number": 620}, {"repo_id": 89558527, "issue_number": 647}, {"repo_id": 89558527, "issue_number": 648}, {"repo_id": 89558527, "issue_number": 649}, {"repo_id": 89558527, "issue_number": 650}]}```

Which looks like it matches the docs.  Any reason why it would be ignored? @azenMatt

**Comment by paltman** [comment]
Nevermind, I wasn't properly sending JSON

**Comment by azenMatt** [comment]
😄 

i'll close this issue now as this has been live for a while

**Comment by AnjaB** [comment]
Issue to Epic: open issue
Select the Epics settings symbol in the sidebar on the right
Click on Convert to Epic
