### ISSUE TITLE
Board data does not report zero estimates for issues

### ISSUE THREAD

**Issue by asimonov-msft** [ZenHubIO/API#39]
When using the Boards view in Chrome, all Issue estimates are displayed as expected (including ones with a value of zero).
When using the REST APIs, non-zero estimates are reported consistently in both the Board data and the individual Issue data. However, estimates set to 0 are not reported in the Board data.

Result of getting Board data (notice that estimate is **not** reported for the issue):
```
{  
   "pipelines":[  
      ...
      {  
         "name":"In Progress",
         "issues":[  
            {  
               "issue_number":62,
               "is_epic":false,
               "position":2
            }
         ]
      }
      ...
   ]
}
```

Result of getting Issue data (notice that estimate **is** reported for the issue):
```
{  
   "estimate":{  
      "value":0
   },
   "plus_ones":[],
   "pipeline":{  
      "name":"In Progress"
   },
   "is_epic":false
}
```

**Comment by azenMatt** [comment]
This is now fixed and should be working as designed to return a '0' value rather than null
