### ISSUE TITLE
REST API endpoint for release reports?

### ISSUE THREAD

**Issue by drwebb** [ZenHubIO/API#48]
Hi, my team uses Zenhub, and we're looking into using the release report features. I'm also a user of the REST API, however I notice that there isn't any documentation on the release reports. Could we get endpoints for the release reports?

**Comment by JimmyLv** [comment]
+1

**Comment by RandallKent** [comment]
This would be great :)

**Comment by azenMatt** [comment]
Hi all, 

The release reports now have API endpoints - https://github.com/ZenHubIO/API#release-reports

please let me know if you have any thoughts on how you would like to see these added to!

**Comment by vinnakota** [comment]
should this work with Zenhub Enterprise 2.20? I get an error when requesting releases for a specific repo. In fact, none of the release report api end points work for me.

        {"message":"URL /p1/repositories/######/reports/releases Not Found"}
