### ISSUE TITLE
API to add dependencies

### ISSUE THREAD

**Issue by HenryGessau** [ZenHubIO/API#53]
https://www.zenhub.com/guides/issue-dependencies
Creating dependencies does not seem to be supported by the API yet.

**Comment by drphilmarshall** [comment]
I'd settle for just being able to get the dependencies with the issue data. Worth a separate issue?

**Comment by ryangrush** [comment]
any update on this? If I could find which PRs are connected to which issues that would help tremendously.

**Comment by kendramoroz** [comment]
Hey @ryangrush thanks for checking in - we haven't added any additional API endpoints just yet but we'll be sure to keep this issue updated once we bump this into progress!

**Comment by Plnda** [comment]
Would love to have this feature

**Comment by tdayton** [comment]
ZenHub's visualization of dependency links is poor enough that I need to create my own visualizations. But apparently I can't get the dependency links from the API. Nor can I export from ZenHub. Are they stored somewhere in GitHub so I can get them from GitHub's API?

**Comment by kendramoroz** [comment]
Hi all - We have Dependency API for the following actions:

- Get Dependencies for a Repository
- Create a Dependency
- Remove a Dependency

If you're team is on ZenHub Enterprise, your admins will have to update to the latest version, 2.27 to get access to these. We are in communication with all team admins to get this upgrade in place!
