### ISSUE TITLE
Should rate limits should return an HTTP 429 not an HTTP 403?

### ISSUE THREAD

**Issue by junketjim** [ZenHubIO/API#6]
I understand the use of Forbidden under this circumstance, but the "Forbidden" will eventually clear when the rate limit resets.

This is what the 429 code was designed for (I think).
Have a look at the HTTP RFC 6585
http://tools.ietf.org/html/rfc6585#section-4

**Comment by acroca** [comment]
You are right @junketjim, but [Github API](https://developer.github.com/v3/#rate-limiting) returns 403 for requests over the limit.
We try to keep our API specs to be easier for anyone to use both GH and ZH apis, that's why we've chosen to return 403 instead of 429 in this case.
