### ISSUE TITLE
Data export for an entire ghe zenhub instance?

### ISSUE THREAD

**Issue by whitmo** [ZenHubIO/API#62]
We over at simple are attempting to analyze our workflows in a kanban fashion and want to get data into our redshift clusters to cross correlate with github issue data, code, prs, etc.

Are there any tools for creating a whole instance event stream (or a batch export for the instance)?

If you can do it by oct 16, we might be able to pay something for it.

**Comment by azenMatt** [comment]
Hi @whitmo - can you please drop us an email at support@zenhub.com and someone will get back to you on this. Thanks
