### ISSUE TITLE
Set estimate endpoint is not working properly

### ISSUE THREAD

**Issue by gaboesquivel** [ZenHubIO/API#64]
The set estimate endpoint is currently returning the following message even with the you send a valid number 

```
{
    "message": "estimate value must be a number NaN undefined"
}
```

![](https://content.screencast.com/users/gaboesquivel5029/folders/Jing/media/f969a0af-953d-4187-b634-050c5e879465/00000013.png)

**Comment by olegzd** [comment]
Can you try again with the body encoded as JSON? Let me know if that fixes the issue.

**Comment by gaboesquivel** [comment]
That was it XD.  Thanks
