### ISSUE TITLE
Set position for an issue

### ISSUE THREAD

**Issue by sheehan** [ZenHubIO/API#65]
I'd like to be able to reorder the issues in a pipeline via the API.

**Comment by pnavarrc** [comment]
Hey @sheehan, Pablo from ZenHub here. You can reorder issues in a Pipeline via the API, you need to use the `POST /p1/repositories/:repo_id/issues/:issue_number/moves` endpoint, passing the target pipeline and position in the request body.

More details in our [API documentation](https://github.com/ZenHubIO/API#move-an-issue-between-pipelines), let us know if you need help!

**Comment by sheehan** [comment]
Thanks @pnavarrc, that works for me!
