### ISSUE TITLE
Api to List events for a repository

### ISSUE THREAD

**Issue by jzumwalt** [ZenHubIO/API#67]
### New Events Endpoint
```
GET https://api.zenhub.io/p1/repositories/<repo>/issues/events
```
Returns a list of the most recent events for all issues sorted by event date.

Similar to Githubs [Api](https://developer.github.com/v3/issues/events/#list-events-for-a-repository).

### Result Size
Obviously this could return an enormous amount of data, support for a `page_size` parameter would be preferred. The response could include a `link` header to indicate `NEXT` and `LAST` pages. 

Alternatively, a `since` parameter could be used to limit the result set, but would introduce an effective limit on the usability for very active repositories.

**Comment by pnavarrc** [comment]
Thanks for your feedback! We already have a request for this endpoint (issue #36), we will update that issue once we have progress on this. Cheers!
