### ISSUE TITLE
有负责中国团队的支持人员吗

### ISSUE THREAD

**Issue by peixl** [ZenHubIO/API#7]
如题

**Comment by zhangchiqing** [comment]
有什么需要帮助的么？我可以回答你的问题。

**Comment by peixl** [comment]
15个试用期后，就不能用了吗

**Comment by zhangchiqing** [comment]
对于Organization的private repo, 15天试用期之后，ZenHub的部分功能将无法使用，比如将无法打开ZenHub Board。
