### ISSUE TITLE
Retrieve pipeline id

### ISSUE THREAD

**Issue by themyth92** [ZenHubIO/API#73]
Hi, is there any way to retrieve the board/pipeline id from your API. We can retrieve that information last time when we call:

```
GET https://api.zenhub.io/p1/repositories/:repo_id/board

Before:
-> "pipelines": [
        {
            "name": "XXXX",
            "id": "YYYY",
            "issues": [...]
        }
]

After:
-> "pipelines": [
        {
            "name": "XXXX",
            "issues": [...]
        }
]

```

But seems like this info has disappeared recently. We need this info to automate moving issues around the board. Thank you.

**Comment by kendramoroz** [comment]
@themyth92 thanks for reporting this! Looks like there might be a bug here - issuing up internally and will report back once we have a fix live. 

CC @olegzd @pnavarrc

**Comment by pnavarrc** [comment]
Hey @themyth92! Pablo from ZenHub here. We just released a fix for this issue, you should be able to run your code without issues now. Cheers!

**Comment by themyth92** [comment]
Cool, tks, working fine now 👍
