### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by zoltanvarhalmi** [ZenHubIO/API#76]
Hi, Can I call ZenHub API from Python? If so, can you help me how I should start it?

I am using pyGitHub for grabbing basic info from orgs/repos, but I also would like to reach out some zenhub features like statuses (board view). 

Any help is very appreciated in advance!

**Comment by pnavarrc** [comment]
Hi @zoltanvarhalmi! you can use any language to make requests to the ZenHub API. In Python, you can use the [requests](http://docs.python-requests.org/en/master/) library to make HTTP requests to the API.

You will need to generate a public API token (see the [ZenHub API Overview](https://github.com/ZenHubIO/API#overview) section for more details) and then use the `requests` package to make requests.

To [get issue data](https://github.com/ZenHubIO/API#get-issue-data), for example, you can use the following code, replacing `<your token>` with your actual public API token.

```python
# Import the requests library
import requests

# Get the issue data for the issue 76 on the repository with ID 47655910
issue_data_endpoint = 'https://api.zenhub.io/p1/repositories/47655910/issues/76'

headers = {
    "X-Authentication-Token": "<your token>"
}

# Make the request
req = requests.get(issue_data_endpoint, headers=headers)

# Print the response as a JSON object
print(req.json())
```

Running this code will print 

```python
{u'pipeline': {u'name': u'Inbox'}, u'plus_ones': [], u'is_epic': False}
```

I hope this helps, let me know if you need further help. Cheers!

**Comment by zoltanvarhalmi** [comment]
@pnavarrc thx a lot!
