### ISSUE TITLE
Not able to export estimate and pipeline data

### ISSUE THREAD

**Issue by AbbuAish** [ZenHubIO/API#77]
I am using MyGit extension in Firefox to export the Github Issues in .csv file but I am not able to download the estimate and pipeline column. I am getting the error "Can't fetch zenhub data for issue: 615. Status: 0". I have configured the zenhub enterprise URL and token but still getting the same error.

**Comment by pnavarrc** [comment]
Hi @AbbuAish!

Are you able to fetch estimates using the ZenHub API directly with the same settings? Here is the [ZenHub API Documentation](https://github.com/ZenHubIO/API), let us know if you need assistance on how to use it.

**Comment by AbbuAish** [comment]
I am able to change the estimate in Zenhub Boards tab. I have not accessed Zenhub API using some code as I am not having development platform available.  I am using MyGit extension to export the data.
