### ISSUE TITLE
How to validate webhook source?

### ISSUE THREAD

**Issue by maxkorp** [ZenHubIO/API#97]
With Github Webhooks, you can configure a secret to validate that the post you receive is really coming from github, and not just a random properly formatted post. 

I don't see anything comparable in the zenhub integration page. One could restrict the allowed source IPs, but I can't find a list of possible IPs anywhere. 

How do you guys suggest validating this info? Do I need to make a request to the api every time I get a hook just to make sure the data is really as it says?

**Comment by veered** [comment]
You could include a random token as a part of the webhook URL you give to Zenhub. Functionally similar to what Github does.

**Comment by maxkorp** [comment]
Yeah, I suppose that's fair. It's not going to be any harder to brute-force a url than to brute-force a secret.
